LEFT_MARGIN = 10
RIGHT_MARGIN_BKD = 5
BAD_GRPS = 0
HIGH_ERROR = 1e10
EXTRACT_Y_MIN = 141
EXTRACT_Y_MAX = 386
EXTRACT_WINDOW = 5
SLITLESS_LEFT = 0
SLITLESS_RIGHT = 72
SLITLESS_TOP = 528
SLITLESS_BOT = 944
GAIN = 5.5

REF_DIR = "/home/stanley/jwst_refs/"
NONLINEAR_FILE = REF_DIR + "jwst_miri_linearity_0032.fits"
DARK_FILE = REF_DIR + "jwst_miri_dark_0084.fits"
FLAT_FILE = REF_DIR + "jwst_miri_flat_0789.fits"
RNOISE_FILE = REF_DIR + "jwst_miri_readnoise_0057.fits"
RESET_FILE = REF_DIR + "jwst_miri_reset_0073.fits"
MASK_FILE = REF_DIR + "jwst_miri_mask_0030.fits"
WCS_FILE = REF_DIR + "jwst_miri_specwcs_0004.fits"
